name: Longitudinal OA multi-omics
navbar:
  title: Longitudinal OA multi-omics
  left:
  - text: Home
    href: index.html
  - text: Activities
    menu:
    - text: Activity 1 - introduction
      href: 01_QC_normalisation.html
    - text: Activity 2 - python poem
      href: 02_EDA.html
    - text: Activity 3 - data analaysis
      href: 03_Differential_expression.html
  - text: Extra resources
    menu:
    - text: Extra activities
      href: 04_Sequencing_QC_normalisation.html
    - text: Additional learning
      href: 05_Sequencing_EDA.html
  - text: About us
    href: about.html
  right:
  - icon: fab fa-github
    text: Source code
    href: https://github.com/ejjohnson93/anderson-peffers_OA
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: flatly
    highlight: textmate
